import { useEffect, useRef, useState } from 'react'
import { useScrollZone } from '@hooks/useScrollZone'
import { HOTSPOTS, SEVERITY_COLORS } from '@data/hotspots'
import { scrollReveal } from '@utils/gsapHelpers'
import DataCard from '@components/ui/DataCard'

export default function Zone1Land({ onEnter }) {
  const zoneRef = useScrollZone(onEnter, 1)
  const mapContainerRef = useRef(null)
  const uiContainerRef = useRef(null)
  const mapRef = useRef(null)
  const [activeHotspot, setActiveHotspot] = useState(null)

  // Calculate total affected population across all hotspots
  const totalAffectedPop = HOTSPOTS.reduce((sum, spot) => sum + spot.affectedPop, 0)

  useEffect(() => {
    if (!mapContainerRef.current) return

    let mapInstance = null

    // Lazy load Leaflet and mapHelpers to split large map code out of main bundle
    import('@utils/mapHelpers').then(({ initializeMap, createMarkerElement, L }) => {
      mapInstance = initializeMap(mapContainerRef.current)
      mapRef.current = mapInstance

      // Add Leaflet markers
      HOTSPOTS.forEach(hotspot => {
        const color = SEVERITY_COLORS[hotspot.severity]
        const el = createMarkerElement(color)
        
        el.addEventListener('mouseenter', () => setActiveHotspot(hotspot))
        el.addEventListener('mouseleave', () => setActiveHotspot(null))
        el.addEventListener('click', (e) => {
          e.stopPropagation()
          setActiveHotspot(prev => prev?.id === hotspot.id ? null : hotspot)
        })

        const customIcon = L.divIcon({
          html: el,
          className: 'leaflet-marker-custom', // Prevent default Leaflet icon styles
          iconSize: [36, 36],
          iconAnchor: [18, 18]
        })

        L.marker(hotspot.coords, { icon: customIcon }).addTo(mapInstance)
      })
    }).catch(err => {
      console.warn('Leaflet dynamic import failed. Falling back gracefully.', err)
    })

    // GSAP Scroll Reveal on UI overlay text
    if (uiContainerRef.current) {
      const children = uiContainerRef.current.querySelectorAll('.scroll-target')
      scrollReveal(children)
    }

    return () => {
      if (mapInstance) mapInstance.remove()
    }
  }, [])

  return (
    <section ref={zoneRef} className="zone relative min-h-screen overflow-hidden" id="Zone1Land">
      {/* Map Container with sepia/blend overlays */}
      <div 
        ref={mapContainerRef} 
        className="absolute inset-0 w-full h-full opacity-60 mix-blend-luminosity sepia grayscale contrast-[1.1] saturate-[1.3] z-0" 
      />

      {/* Overlay UI - Bottom-anchored on mobile, Right-aligned on desktop */}
      <div 
        ref={uiContainerRef}
        className="absolute inset-x-0 bottom-0 md:inset-0 pointer-events-none flex items-end md:items-center justify-center md:justify-end p-4 md:p-0 md:pr-[10%] z-20"
      >
        <div className="w-full max-w-md md:w-[420px] pointer-events-auto bg-earth-dark/95 md:bg-earth-dark/40 p-6 md:p-8 rounded-t-2xl md:rounded-2xl border border-white/10 md:border-white/5 backdrop-blur-lg md:backdrop-blur-sm shadow-2xl">
          <h2 className="scroll-target text-3xl md:text-4xl font-bold text-sand-light mb-4 md:mb-6">
            The Landscape
          </h2>
          <p className="scroll-target text-haze-grey mb-6 md:mb-8 text-xs md:text-sm leading-relaxed">
            The Raipur–Bhilai–Durg corridor is a dense industrial belt. Here, the primary threat is not gaseous, but coarse particulate matter (PM10) generated by mining, manufacturing, and unpaved infrastructure.
          </p>

          {/* Dynamic Data Card on Hover */}
          <div className="scroll-target min-h-[180px] md:min-h-[220px] mb-4 md:mb-6">
            {activeHotspot ? (
              <div className="animate-fade-in">
                <DataCard 
                  title={activeHotspot.name}
                  value={activeHotspot.pm10}
                  unit="µg/m³ PM10"
                  sub={activeHotspot.description}
                  color={SEVERITY_COLORS[activeHotspot.severity]}
                  animate={true}
                />
              </div>
            ) : (
              <div className="text-haze-grey text-[10px] md:text-xs italic opacity-60 border border-white/10 rounded-xl p-5 md:p-6 text-center bg-black/20">
                Hover over a pulsing hotspot on the map to inspect local PM10 readings.
              </div>
            )}
          </div>

          {/* Total Affected Population Stat Bar */}
          <div className="scroll-target border-t border-white/10 pt-4 md:pt-6 flex justify-between items-center">
            <div>
              <div className="text-[9px] md:text-[10px] text-haze-grey tracking-wider uppercase">
                Corridor Risk Exposure
              </div>
              <div className="text-lg md:text-xl font-bold text-sand-light font-mono mt-1">
                {totalAffectedPop.toLocaleString()}+
              </div>
            </div>
            <div className="text-[9px] md:text-[10px] text-right text-rust-red font-mono uppercase bg-rust-red/10 border border-rust-red/20 px-2.5 py-1 rounded">
              Active Warning
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
