import { useEffect, useRef, useState } from 'react'
import { useScrollZone } from '@hooks/useScrollZone'
import mapboxgl from 'mapbox-gl'
import { initializeMap, createMarkerElement } from '@utils/mapHelpers'
import { HOTSPOTS, SEVERITY_COLORS } from '@data/hotspots'
import DataCard from '@components/ui/DataCard'

export default function Zone1Land({ onEnter }) {
  const zoneRef = useScrollZone(onEnter, 1)
  const mapContainerRef = useRef(null)
  const mapRef = useRef(null)
  const [activeHotspot, setActiveHotspot] = useState(null)

  useEffect(() => {
    if (!mapContainerRef.current) return

    // Initialize Mapbox map
    mapRef.current = initializeMap(mapContainerRef.current)

    // Add markers
    HOTSPOTS.forEach(hotspot => {
      const color = SEVERITY_COLORS[hotspot.severity]
      const el = createMarkerElement(color)
      
      el.addEventListener('mouseenter', () => setActiveHotspot(hotspot))
      el.addEventListener('mouseleave', () => setActiveHotspot(null))

      new mapboxgl.Marker({ element: el })
        .setLngLat([hotspot.coords[1], hotspot.coords[0]]) // Mapbox expects [lng, lat]
        .addTo(mapRef.current)
    })

    return () => {
      if (mapRef.current) mapRef.current.remove()
    }
  }, [])

  return (
    <section ref={zoneRef} className="zone relative" id="Zone1Land">
      {/* Mapbox Container */}
      <div 
        ref={mapContainerRef} 
        className="absolute inset-0 w-full h-full opacity-60 mix-blend-luminosity" 
        style={{ filter: 'sepia(1) hue-rotate(-30deg) saturate(1.5)' }} // Blend with dust theme
      />

      {/* Overlay UI */}
      <div className="absolute inset-0 pointer-events-none flex items-center justify-end pr-[10%]">
        <div className="w-[400px] pointer-events-auto">
          <h2 className="text-4xl font-bold text-sand-light mb-6">The Landscape</h2>
          <p className="text-haze-grey mb-8">
            The Raipur–Bhilai–Durg corridor is a dense industrial belt. Here, the primary threat is not gaseous, but coarse particulate matter (PM10) generated by mining, manufacturing, and unpaved infrastructure.
          </p>

          {/* Dynamic Data Card on Hover */}
          <div className="min-h-[200px] transition-opacity duration-300" style={{ opacity: activeHotspot ? 1 : 0 }}>
            {activeHotspot && (
              <DataCard 
                title={activeHotspot.name}
                value={activeHotspot.pm10}
                unit="µg/m³ PM10"
                sub={activeHotspot.description}
                color={SEVERITY_COLORS[activeHotspot.severity]}
              />
            )}
            {!activeHotspot && (
              <div className="text-haze-grey text-sm italic opacity-50">
                Hover over a glowing hotspot on the map to view data.
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  )
}
