import { useEffect, useRef, useState } from 'react'
import { useScrollZone } from '@hooks/useScrollZone'
import mapboxgl from 'mapbox-gl'
import { initializeMap, createMarkerElement } from '@utils/mapHelpers'
import { HOTSPOTS, SEVERITY_COLORS } from '@data/hotspots'
import { scrollReveal } from '@utils/gsapHelpers'
import DataCard from '@components/ui/DataCard'

export default function Zone1Land({ onEnter }) {
  const zoneRef = useScrollZone(onEnter, 1)
  const mapContainerRef = useRef(null)
  const uiContainerRef = useRef(null)
  const mapRef = useRef(null)
  const [activeHotspot, setActiveHotspot] = useState(null)

  // Calculate total affected population across all hotspots
  const totalAffectedPop = HOTSPOTS.reduce((sum, spot) => sum + spot.affectedPop, 0)

  useEffect(() => {
    if (!mapContainerRef.current) return

    // Initialize Mapbox map
    mapRef.current = initializeMap(mapContainerRef.current)

    // Add markers
    HOTSPOTS.forEach(hotspot => {
      const color = SEVERITY_COLORS[hotspot.severity]
      const el = createMarkerElement(color)
      
      // Target the dot inside the custom marker container to hook hover details
      el.addEventListener('mouseenter', () => setActiveHotspot(hotspot))
      el.addEventListener('mouseleave', () => setActiveHotspot(null))

      new mapboxgl.Marker({ element: el })
        .setLngLat([hotspot.coords[1], hotspot.coords[0]]) // Mapbox expects [lng, lat]
        .addTo(mapRef.current)
    })

    // GSAP Scroll Reveal on UI overlay text
    if (uiContainerRef.current) {
      const children = uiContainerRef.current.querySelectorAll('.scroll-target')
      scrollReveal(children)
    }

    return () => {
      if (mapRef.current) mapRef.current.remove()
    }
  }, [])

  return (
    <section ref={zoneRef} className="zone relative" id="Zone1Land">
      {/* Mapbox Container with Tailwind v4 filter blend modes */}
      <div 
        ref={mapContainerRef} 
        className="absolute inset-0 w-full h-full opacity-60 mix-blend-luminosity sepia grayscale contrast-[1.1] saturate-[1.3]" 
      />

      {/* Overlay UI */}
      <div 
        ref={uiContainerRef}
        className="absolute inset-0 pointer-events-none flex items-center justify-end pr-[8%] md:pr-[10%]"
      >
        <div className="w-[420px] pointer-events-auto bg-earth-dark/40 p-8 rounded-2xl border border-white/5 backdrop-blur-sm">
          <h2 className="scroll-target text-4xl font-bold text-sand-light mb-6">
            The Landscape
          </h2>
          <p className="scroll-target text-haze-grey mb-8 text-sm leading-relaxed">
            The Raipur–Bhilai–Durg corridor is a dense industrial belt. Here, the primary threat is not gaseous, but coarse particulate matter (PM10) generated by mining, manufacturing, and unpaved infrastructure.
          </p>

          {/* Dynamic Data Card on Hover */}
          <div className="scroll-target min-h-[220px] mb-6">
            {activeHotspot ? (
              <div className="animate-fade-in">
                <DataCard 
                  title={activeHotspot.name}
                  value={activeHotspot.pm10}
                  unit="µg/m³ PM10"
                  sub={activeHotspot.description}
                  color={SEVERITY_COLORS[activeHotspot.severity]}
                />
              </div>
            ) : (
              <div className="text-haze-grey text-xs italic opacity-60 border border-white/10 rounded-xl p-6 text-center bg-black/20">
                Hover over a pulsing hotspot on the map to inspect local PM10 readings.
              </div>
            )}
          </div>

          {/* Total Affected Population Stat Bar */}
          <div className="scroll-target border-t border-white/10 pt-6 flex justify-between items-center">
            <div>
              <div className="text-[10px] text-haze-grey tracking-wider uppercase">
                Corridor Risk Exposure
              </div>
              <div className="text-xl font-bold text-sand-light font-mono mt-1">
                {totalAffectedPop.toLocaleString()}+
              </div>
            </div>
            <div className="text-[10px] text-right text-rust-red font-mono uppercase bg-rust-red/10 border border-rust-red/20 px-2.5 py-1 rounded">
              Active Warning
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
